### ISSUE TITLE
crash on MC start (1.9.4)

### ISSUE THREAD

**Issue by Cat-McCatface** [hea3ven/DulceDeLeche#1]
MC (1.9.4. forge version 1954) crashes before getting to loading screen with mod enabled. appears to be a forge bug but log eventually gets to the mod's bootstrap code. tested with mod version 1.0.0. crash doesn't occur when DulceDeLeche is removed from mod folder.

log: http://pastebin.com/WciR3vaW

**Comment by hea3ven** [comment]
Should be fixed in version 1.9.4-1.0.1
