### ISSUE TITLE
[19w12b] Game crashes during preInit of the Enchantments module

### ISSUE THREAD

**Issue by Shnupbups** [hea3ven/DulceDeLeche#12]
Attempting to launch the game in 19w12b will cause a crash during preInit of the Enchantments module. This happens regardless if said module is disabled in the config.

The particular error is:
`java.lang.NoClassDefFoundError: net/minecraft/enchantment/Enchantment`

**Comment by hea3ven** [comment]
Fixed in 1.2.2-29
