### ISSUE TITLE
crash when using area enchantment

### ISSUE THREAD

**Issue by spyguy26** [hea3ven/DulceDeLeche#6]
using:
dulcedeleche-1.1.2-7
fabric-0.1.5.88
mapping/game: 19w05a.6
loader: 0.3.5.106

game crashes when using a tool with the area enchantment here's the log
https://gist.github.com/spyguy26/41b35d5dc8c0245c6659a20242863f31

**Comment by hea3ven** [comment]
Fixed in dulcedeleche-1.1.2-9.
