### ISSUE TITLE
[Fabric 19w09a] Blocks do not drop themselves in Survival

### ISSUE THREAD

**Issue by Shnupbups** [hea3ven/DulceDeLeche#7]
In Survival, mining either of the blocks (the Workbench or the Assembler) will instantly destroy it, dropping only their contents and not the blocks themselves.

How to reproduce:

1. Place either a Workbench or Assembler in the world
2. In survival mode, mine the block

**Comment by hea3ven** [comment]
Fixed in version 1.2.1-24
